### ISSUE TITLE
Error while loading the tutorial in mybinder

### ISSUE THREAD

**Issue by ELpolloGUAPO** [kwant-project/kwant-tutorial-2016#1]
Hello all,

I am new to computational nanoelectronics and wanted to check out your tutorial, but get the following error:
![image](https://github.com/kwant-project/kwant-tutorial-2016/assets/40899576/18566f6a-5067-44e5-89a1-35e03e67d800)
Is it possible to fix it?
Thanks in advance,
Best regards,

**Comment by akhmerov** [comment]
Should be fixed; please try again.
